### ISSUE TITLE
Level of SEO and Dynamic Content Support

### ISSUE THREAD

**Issue by MohammedMaaz** [baobabKoodaa/gatsby-starter-infinite-scroll#3]
First of all, I would like to say that @baobabKoodaa nice work done in this starter kit, specially handling those edge cases seamlessly which really matter for a scalable and reliable production app.

However, one thing that concerns me in this regard is lets consider a scenario of an ecommerce website having hundreds of products being dynamically updated and added in the database, moreover, each product's content and meta is critical with regards to SEO and web crawlers, in addition to that I would like to lazily load content from the server in batches (infinite scrolling).

My question is that is Gatsby still a good choice for this use case provided that I use this infinite scroll starter kit. Since it really lazily loads content from the server (not a mere client side filtering), what levels of SEO support does it provide for content that lazily loads on scrolling and is not present initially. 

Moreover, does it statically generate content at the build time and then pass that content in chunks to the client one by one? In that case is there any solution if my content is dynamic and I want to give features to my users such as filter and sort content (products) based on different criterias and sort fields that too while lazily loading (only the content that is reqd. on the client) from the server.

I know this is more of a question on gatsby's limitations in general and not necessarily regarding this starter, but since I saw your intention of solving this infinite scroll problem for real use cases, I thought that may be you have solution to those scenarios is mind too, or please correct me if I'm missing something because I'm relatively new to this Gatsby world.

**Comment by baobabKoodaa** [comment]
Hi @MohammedMaaz ! I'm glad to hear you like the starter. I understand that you want to use dynamic content instead of static content, and you want the website to be easily crawlable for web crawlers for SEO purposes.

> if my content is dynamic and I want to give features to my users such as filter and sort content (products) based on different criterias and sort fields that too while lazily loading (only the content that is reqd. on the client) from the server.

The way that the starter is set up, we have a "fake API" where the frontend makes request at runtime. For example, when the user scrolls down, the frontend might send a request "please give me items for page 8". Normally you would have a backend server providing an API to respond to these requests. However, since this is a static site generator, we don't have a backend, we have simply pregenerated all the responses at build time, as you suspected. So all the responses are simply static JSON files.

If you were to switch from static content to dynamic content, you wouldn't have these pregenerated responses, you would instead have a backend server somewhere providing this API. If you have a real API already for your real use case, it should be fairly straightforward to modify this starter to fetch items from the real API instead of the fake API. If you want filtering and sorting to be done on server side, then you would have to implement these features on your backend. All of this sounds like reasonable to me.

> Since it really lazily loads content from the server (not a mere client side filtering), what levels of SEO support does it provide for content that lazily loads on scrolling and is not present initially.

Right now the starter provides a paginated alternative to infinite scrolling. These paginated pages are easily crawlable (SEO support). _However_, if you were to change from static content to dynamic content, you wouldn't be able to generate these paginated pages. This would be an issue for your SEO.

I have not personally worked on SEO, so I'm not the best person to answer how to make a site with dynamic content easily crawlable. But this sounds like a very generic problem that many people have faced, so you will probably find a lot of resources online about ways to resolve the issue. Let me know what you find :)
